services:
  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: listo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    volumes:
      - users-db:/var/lib/postgresql/data
    networks:
      - auth-service-network
  auth-service: 
    build: ./auth
    depends_on:
      - auth-db
    expose:
      - 8080
    networks:
      - auth-service-network
networks: 
  auth-service-network:
    driver: bridge
volumes: 
  users-db: