ROLES = [
    "admin",
    "user",
    "car owner", 
    "renter",
]

PERMISSIONS = {
    "admin": [
        "list users",
        "ban user",
        "unban user",
        "review reports",
        "list cars",
        "remove car",
        "flag car",
        "list rentals",
        "cancel rental",
        "issue refund",
        "list announcements",
        "create announcement",
        "edit announcement",
        "delete announcement",
        "access analytics",
        "export reports",
        "monitor system",
        "monitor user activity",
        "manage settings",
        "access settings",
        "list roles",
        "manage roles",
        "list permissions",
        "list disputes",
        "resolve disputes",
        "list issues",
        "resolve issues",
    ],
    "user": [
        "verify identity",
        "link payment method",
        "edit profile",
        "view dashboard",
        "logout",
    ],
    "car owner": [
        "list cars",
        "add car",
        "edit car",
        "remove car",
        "view rental history",
        "manage rental requests",
        "chat with renters",
        "manage availability",
        "set pricing",
        "view earnings",
        "view payout status",
        "view upcoming rentals",
        "report dispute",
        "report issue",
    ],
    "renter": [
        "list cars",
        "search cars",
        "view owner profile",
        "send rental request",
        "pay for rental",
        "modify rental request",
        "cancel rental request",
        "chat with owner",
        "review rental",
        "review owner",
        "report issue",
    ],
}